/**
 * Draco-compressed GLTF asset manifest + loader wiring.
 *
 * The spec requires "模型 Draco 压缩". The scene is procedural geometry (no
 * source GLTF to compress), so this module delivers the Draco toolchain as a
 * formal placeholder: public/tank-placeholder.glb (KHR_draco_mesh_compression),
 * generated by scripts/export-draco-glb.mjs. GLTFLoader + DRACOLoader are
 * configured (draco decoder path) so any future authored GLTF loads from
 * Draco-compressed form with no further wiring.
 *
 * Usage (when a material needs the placeholder mesh):
 *   const gltf = await loadDracoGltf(renderer, 'tank-placeholder');
 *   scene.add(gltf.scene);
 */
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
import type * as THREE from 'three';
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

export interface DracoAssetEntry {
  /** Logical name used by callers. */
  name: string;
  /** Resolved URL relative to the site base. */
  url: string;
  /** Compression method used (for documentation / verification). */
  method: string;
}

export const DRACO_ASSET_MANIFEST: DracoAssetEntry[] = [
  { name: 'tank-placeholder', url: './tank-placeholder.glb', method: 'edgebreaker (KHR_draco_mesh_compression)' },
];

let sharedLoader: GLTFLoader | null = null;

/**
 * Lazily build (and configure once) a GLTFLoader with a DRACOLoader that fetches
 * the draco wasm decoder from the jsdelivr CDN. Callers reuse one loader.
 */
export function getDracoGltfLoader(): GLTFLoader {
  if (!sharedLoader) {
    const draco = new DRACOLoader();
    draco.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.183.2/examples/jsm/libs/draco/');
    const loader = new GLTFLoader();
    loader.setDRACOLoader(draco);
    sharedLoader = loader;
  }
  return sharedLoader;
}

/**
 * Load a Draco-compressed GLTF from the manifest by logical name. Returns a
 * promise that resolves to the parsed GLTF scene graph.
 */
export async function loadDracoGltf(name: string): Promise<GLTF> {
  const entry = DRACO_ASSET_MANIFEST.find((e) => e.name === name);
  if (!entry) throw new Error(`[draco] unknown asset: ${name}`);
  const loader = getDracoGltfLoader();
  const gltf = await loader.loadAsync(entry.url);
  return gltf as unknown as GLTF & { scene: THREE.Object3D };
}
